/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/issue": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Issue one or more signed credentials
         * @description Issues one signed `Credential` per requested type.  The server computes
         *     the Poseidon2 commitment over the attribute value and salt, signs it with
         *     its secp256k1 `ISSUER_PRIVATE_KEY`, and returns the full credential
         *     objects for the holder to store locally.
         *
         *     **Identity verification flow (Persona)**
         *
         *     When `kyc` is included in `credential_types` and `PERSONA_API_KEY` is
         *     configured, the first call returns HTTP 202 with a `personaUrl` redirect.
         *     After the user completes the Persona flow and returns, re-send the
         *     original request body with `persona_inquiry_id` set to the ID from the
         *     202 response.
         *
         *     **Funds verification flow (Plaid)**
         *
         *     When `funds` is included, the server calls Plaid to fetch the holder's
         *     verified bank balance.  No `attributes.balance` value from the client
         *     is used — Plaid is the source of truth.
         *
         *     **Demo mode**
         *
         *     If `PERSONA_API_KEY` / `PLAID_ACCESS_TOKEN` are absent the server uses
         *     safe demo fallbacks (always passes / returns $50 000) so the app works
         *     without third-party credentials.
         */
        post: operations["issueCredentials"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/witness": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Generate a ZK witness for a credential
         * @description Executes the Noir circuit for the given credential type server-side and
         *     returns the serialised witness bytes as a hex string.
         *
         *     The witness is private — it encodes all inputs (value, salt, sig, …)
         *     needed by Barretenberg (`bb.js`) to produce a UltraHonk proof.
         *
         *     **Note:** the browser can run this step directly via `noir_js` + WASM.
         *     This endpoint exists as a server-side fallback for environments where
         *     WASM execution is inconvenient.
         */
        post: operations["generateWitness"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Liveness probe
         * @description Always returns HTTP 200 `{ "status": "ok" }`.  Use this as a liveness check — if the process is alive, it responds.  For a deeper readiness check (RPC reachable, contracts configured, signer key set) use `/api/ready` instead.
         */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Readiness probe
         * @description Checks all runtime dependencies and returns a structured status
         *     for each.  Returns HTTP 200 only when **all** checks pass; HTTP 503
         *     when any check fails.
         *
         *     | Dependency | What is checked |
         *     |---|---|
         *     | `signer` | `ISSUER_PRIVATE_KEY` env var is set |
         *     | `contracts` | All `NEXT_PUBLIC_*` contract addresses are set |
         *     | `rpc` | Stellar RPC responds to `getNetwork` within 5 s |
         *     | `persona` | `PERSONA_API_KEY` unset (demo OK) or `PERSONA_KYC_TEMPLATE_ID` also set |
         */
        get: operations["getReady"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/issuers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List registered issuers
         * @description Returns all active (non-revoked) issuers from the on-chain
         *     `IssuerRegistry` contract via Soroban simulation.
         *
         *     Returns an empty array when `NEXT_PUBLIC_ISSUER_REGISTRY_ID` is not
         *     configured.  Revoked issuers are filtered out before the response.
         */
        get: operations["listIssuers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/plaid-balance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Fetch verified bank balance via Plaid
         * @description Fetches the holder's verified bank balance from Plaid and returns the
         *     highest available balance across all depository accounts.
         *
         *     **Mock mode:** when `PLAID_ACCESS_TOKEN` is not set the endpoint
         *     returns `{ "balance": 50000, "mock": true }` so the app works without
         *     a real Plaid integration.
         *
         *     **Production mode:** returns `{ "balance": <highest depository balance>,
         *     "accounts": [...] }` where each account has `name` and `available`.
         *
         *     This value is used as the `funds` credential attribute — the user cannot
         *     supply their own balance.
         */
        get: operations["getPlaidBalance"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description | Value | Proves |
         *     |---|---|
         *     | `kyc` | Identity verified |
         *     | `age` | Age ≥ threshold |
         *     | `jurisdiction` | Country not restricted |
         *     | `income` | Income ≥ threshold |
         *     | `funds` | Balance ≥ threshold |
         *     | `accreditation` | Net worth ≥ threshold |
         * @example kyc
         * @enum {string}
         */
        CredentialType: "kyc" | "age" | "jurisdiction" | "income" | "funds" | "accreditation";
        /** @description Optional per-type parameters that are embedded in the credential and verified by the on-chain circuit.  All fields are optional; omitted fields use the circuit's default value. */
        ClaimParams: {
            /**
             * @description Minimum age in years (age circuit). Default "18".
             * @example 21
             */
            threshold_years?: string;
            /**
             * @description Numeric threshold for income / funds / accreditation circuits. Units: USD cents-free integer (e.g. `"50000"` = $50 000).
             * @example 50000
             */
            threshold?: string;
            /**
             * @description ISO 3166-1 numeric country codes to block (jurisdiction circuit). Array is zero-padded to exactly 8 entries.  Default blocks US (840), Iran (364), and North Korea (408).
             * @example [
             *       "840",
             *       "364",
             *       "408",
             *       "0",
             *       "0",
             *       "0",
             *       "0",
             *       "0"
             *     ]
             */
            restricted?: string[];
        };
        /** @description A signed credential returned by `/api/issue`.  The holder stores this locally (never on-chain) and uses it as private input when generating a ZK proof. */
        Credential: {
            type: components["schemas"]["CredentialType"];
            /**
             * @description Human-readable credential title.
             * @example KYC Complete
             */
            title: string;
            /**
             * @description Human-readable claim description.
             * @example identity verified
             */
            claim: string;
            /**
             * @description Display name of the issuing authority.
             * @example StellarCred Authority
             */
            issuer: string;
            /**
             * @description Stellar account address of the registered issuer.
             * @example GABC...XYZ
             */
            issuerId: string;
            /**
             * @description Stellar account address of the credential holder.
             * @example GDEF...UVW
             */
            holder: string;
            /**
             * @description The circuit preimage (private input).  For `kyc` this is a random field element; for `age` it is days-since-epoch; for numeric types it is an integer string.
             * @example 18900
             */
            value: string;
            /**
             * @description Random 31-byte field element used in the Poseidon2 commitment.
             * @example 0x1a2b3c...
             */
            salt: string;
            /**
             * @description Poseidon2([value, salt], 2) — the public input committed to on-chain.
             * @example 0xdeadbeef...
             */
            commitment: string;
            /**
             * @description secp256k1 DER signature bytes (issuer signs the raw commitment).
             * @example [
             *       48,
             *       68,
             *       2,
             *       32
             *     ]
             */
            sig: number[];
            /** @description 32-byte big-endian X coordinate of the issuer's secp256k1 public key. */
            issuerPubX: number[];
            /** @description 32-byte big-endian Y coordinate of the issuer's secp256k1 public key. */
            issuerPubY: number[];
            /**
             * @description Unix timestamp (seconds) when the credential was issued.
             * @example 1722268547
             */
            issuedAt: number;
            /**
             * @description Duration string or absolute timestamp string.  Duration format: `"N days"` (e.g. `"90 days"`).
             * @example 90 days
             */
            expiry: string;
            claimParams?: components["schemas"]["ClaimParams"];
        };
        ErrorResponse: {
            /**
             * @description Human-readable error message.
             * @example holder address is required
             */
            error: string;
        };
        DependencyStatus: {
            /** @enum {string} */
            status: "ok" | "error";
            /**
             * @description Extra detail when status is "error".
             * @example Missing: proofRegistry
             */
            message?: string;
        };
        SignerStatus: components["schemas"]["DependencyStatus"] & {
            /**
             * @description `"configured"` when `ISSUER_PRIVATE_KEY` env var is set; `"demo"` when the app is running with the public fallback key.
             * @example configured
             * @enum {string}
             */
            issuer: "demo" | "configured";
        };
        /** @description Structured readiness check returned by `/api/ready`. */
        ReadyResponse: {
            /**
             * @description `true` only when all four dependency checks pass.
             * @example true
             */
            ready: boolean;
            signer: components["schemas"]["SignerStatus"];
            contracts: components["schemas"]["DependencyStatus"];
            rpc: components["schemas"]["DependencyStatus"];
            persona: components["schemas"]["DependencyStatus"];
        };
        /** @description Response when `PLAID_ACCESS_TOKEN` is not configured (demo mode). */
        PlaidBalanceMockResponse: {
            /**
             * @description Mock balance of $50 000.
             * @example 50000
             */
            balance: number;
            /**
             * @description Always `true` in mock mode.
             * @example true
             */
            mock: boolean;
        };
        /** @description Response when Plaid returns real account data. */
        PlaidBalanceRealResponse: {
            /**
             * @description Highest available balance across depository accounts (USD integer).
             * @example 12500
             */
            balance: number;
            /** @description All depository accounts, sorted by available balance descending. */
            accounts: {
                /**
                 * @description Account display name from Plaid.
                 * @example Checking
                 */
                name: string;
                /**
                 * @description Available balance in USD (integer).
                 * @example 12500
                 */
                available: number;
            }[];
        };
        RegisteredIssuer: {
            /**
             * @description Stellar account address of the issuer.
             * @example GABC...XYZ
             */
            id: string;
            /**
             * @description Display name (from `NEXT_PUBLIC_ISSUER_NAMES` env or truncated address).
             * @example StellarCred Authority
             */
            name: string;
            /**
             * @description Hex-encoded secp256k1 public key (x || y, 64 bytes = 128 hex chars).
             * @example 04abcd...
             */
            pubkeyHex: string;
            /**
             * @description Credential types this issuer is authorised to issue.
             * @example [
             *       "kyc",
             *       "age",
             *       "jurisdiction"
             *     ]
             */
            credentialTypes: components["schemas"]["CredentialType"][];
            /**
             * @description Always `false` in this response — revoked issuers are filtered out.
             * @example false
             */
            revoked: boolean;
        };
    };
    responses: never;
    parameters: {
        /** @description Caller-supplied correlation ID.  Echoed back in the `X-Request-Id` response header.  Server generates a UUID v4 when omitted. */
        RequestId: string;
    };
    requestBodies: never;
    headers: {
        /** @description Correlation ID (supplied or generated). */
        XRequestId: string;
    };
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    issueCredentials: {
        parameters: {
            query?: never;
            header?: {
                /** @description Caller-supplied correlation ID.  Echoed back in the `X-Request-Id` response header.  Server generates a UUID v4 when omitted. */
                "X-Request-Id"?: components["parameters"]["RequestId"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /**
                     * @description One or more credential types to issue in a single call. Duplicates are de-duplicated server-side. Preferred over the deprecated `type` field.
                     * @example [
                     *       "kyc",
                     *       "age"
                     *     ]
                     */
                    credential_types?: components["schemas"]["CredentialType"][];
                    /**
                     * @description Stellar account address of the credential holder.
                     * @example GDEF...UVW
                     */
                    holder: string;
                    /**
                     * @description Stellar account address of the issuer whose key is registered in `IssuerRegistry`.  Must match the server's `ISSUER_PRIVATE_KEY`.
                     * @example GABC...XYZ
                     */
                    issuerId: string;
                    /**
                     * @description Display name embedded in every issued credential.
                     * @default StellarCred Authority
                     * @example StellarCred Authority
                     */
                    issuerName?: string;
                    /**
                     * @description Duration string (`"N days"`) or Unix timestamp string. Embedded in the credential; not enforced on-chain until `ProofRegistry` checks it at proof submission.
                     * @default 90 days
                     * @example 90 days
                     */
                    expiry?: string;
                    /**
                     * @description Type-specific attribute fields.  Required keys per type:
                     *
                     *     | Type | Required key | Format |
                     *     |------|-------------|--------|
                     *     | `age` | `date_of_birth` | `YYYY-MM-DD` |
                     *     | `income` | `income` | Integer string (USD) |
                     *     | `jurisdiction` | `country_code` | ISO 3166-1 numeric string |
                     *     | `accreditation` | `net_worth` | Integer string (USD) |
                     *     | `kyc` | _(none — auto)_ | — |
                     *     | `funds` | _(overridden by Plaid)_ | — |
                     * @example {
                     *       "date_of_birth": "1990-06-15",
                     *       "country_code": "566"
                     *     }
                     */
                    attributes?: {
                        [key: string]: string;
                    };
                    claimParams?: components["schemas"]["ClaimParams"];
                    /**
                     * @description Persona inquiry ID returned by the 202 response.  Include on the follow-up request after the user returns from the Persona hosted flow.
                     * @example inq_abc123
                     */
                    persona_inquiry_id?: string;
                    /**
                     * Format: uri
                     * @description URL to redirect the user back to after Persona verification. Appended as `?return_url=…` on the StellarCred verify page.
                     * @example https://yourapp.xyz/deposit
                     */
                    returnUrl?: string;
                    /**
                     * @deprecated
                     * @description **Deprecated** — use `credential_types` instead. Legacy single-type field; still accepted for backwards compatibility.
                     */
                    type?: components["schemas"]["CredentialType"];
                    /**
                     * @deprecated
                     * @description **Deprecated** — use `attributes` instead. Legacy single-attribute value; mapped to the correct key based on `type`.
                     */
                    attribute?: string;
                };
            };
        };
        responses: {
            /** @description All requested credentials issued successfully. */
            200: {
                headers: {
                    "X-Request-Id": components["headers"]["XRequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @description One credential per requested type, in request order. */
                        credentials: components["schemas"]["Credential"][];
                    };
                };
            };
            /**
             * @description Identity verification required.  The holder must visit `personaUrl`
             *     to complete the Persona KYC flow, then re-send the original request
             *     with `persona_inquiry_id` set.
             */
            202: {
                headers: {
                    "X-Request-Id": components["headers"]["XRequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example true */
                        needsPersona: boolean;
                        /**
                         * Format: uri
                         * @description Persona hosted-flow URL to redirect the user to.
                         * @example https://withpersona.com/verify?inquiry-id=inq_abc123
                         */
                        personaUrl: string;
                        /**
                         * @description Persona inquiry ID; pass back as `persona_inquiry_id`.
                         * @example inq_abc123
                         */
                        inquiryId: string;
                    };
                };
            };
            /**
             * @description Bad request.  Possible causes:
             *     - `credential_types` is empty or contains an unknown type
             *     - `holder` or `issuerId` is missing
             *     - Request body is not valid JSON
             */
            400: {
                headers: {
                    "X-Request-Id": components["headers"]["XRequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /**
             * @description Identity or balance verification failed, or issuer key mismatch.
             *     Possible causes:
             *     - Persona inquiry was not approved
             *     - Plaid balance verification failed
             *     - `ISSUER_PRIVATE_KEY` does not match the on-chain registered key
             *       for the requested `issuerId`
             */
            403: {
                headers: {
                    "X-Request-Id": components["headers"]["XRequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /**
             * @description Internal server error.  Possible causes:
             *     - Commitment or signing step failed
             *     - `PERSONA_API_KEY` set but `PERSONA_KYC_TEMPLATE_ID` missing
             */
            500: {
                headers: {
                    "X-Request-Id": components["headers"]["XRequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    generateWitness: {
        parameters: {
            query?: never;
            header?: {
                /** @description Caller-supplied correlation ID.  Echoed back in the `X-Request-Id` response header.  Server generates a UUID v4 when omitted. */
                "X-Request-Id"?: components["parameters"]["RequestId"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    type: components["schemas"]["CredentialType"];
                    credential: components["schemas"]["Credential"];
                };
            };
        };
        responses: {
            /** @description Witness generated successfully. */
            200: {
                headers: {
                    "X-Request-Id": components["headers"]["XRequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /**
                         * @description Serialised witness as a lowercase hex string. Pass this to `bb.js` `UltraHonkBackend.generateProof()`.
                         * @example 1a2b3c...
                         */
                        witness: string;
                    };
                };
            };
            /** @description Missing or invalid request body. */
            400: {
                headers: {
                    "X-Request-Id": components["headers"]["XRequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Circuit execution failed (e.g. invalid credential inputs). */
            500: {
                headers: {
                    "X-Request-Id": components["headers"]["XRequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service is alive. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /**
                         * @example ok
                         * @enum {string}
                         */
                        status: "ok";
                    };
                };
            };
            /** @description Method not allowed (only GET is accepted). */
            405: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getReady: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description All dependencies are ready. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "ready": true,
                     *       "signer": {
                     *         "status": "ok",
                     *         "issuer": "configured"
                     *       },
                     *       "contracts": {
                     *         "status": "ok"
                     *       },
                     *       "rpc": {
                     *         "status": "ok"
                     *       },
                     *       "persona": {
                     *         "status": "ok"
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["ReadyResponse"];
                };
            };
            /** @description Method not allowed (only GET is accepted). */
            405: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description One or more dependencies are not ready. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "ready": false,
                     *       "signer": {
                     *         "status": "error",
                     *         "message": "ISSUER_PRIVATE_KEY not set — signing with the public demo issuer key",
                     *         "issuer": "demo"
                     *       },
                     *       "contracts": {
                     *         "status": "error",
                     *         "message": "Missing: proofRegistry, credentialVerifier"
                     *       },
                     *       "rpc": {
                     *         "status": "ok"
                     *       },
                     *       "persona": {
                     *         "status": "ok",
                     *         "message": "not configured (demo mode)"
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["ReadyResponse"];
                };
            };
        };
    };
    listIssuers: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Issuer list retrieved (may be empty). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        issuers: components["schemas"]["RegisteredIssuer"][];
                    };
                };
            };
            /** @description Method not allowed (only GET is accepted). */
            405: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description On-chain simulation failed. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example Failed to fetch issuers */
                        error: string;
                        /** @description Always an empty array on error. */
                        issuers: unknown[];
                    };
                };
            };
        };
    };
    getPlaidBalance: {
        parameters: {
            query?: never;
            header?: {
                /** @description Caller-supplied correlation ID.  Echoed back in the `X-Request-Id` response header.  Server generates a UUID v4 when omitted. */
                "X-Request-Id"?: components["parameters"]["RequestId"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Balance fetched (real or mock). */
            200: {
                headers: {
                    "X-Request-Id": components["headers"]["XRequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlaidBalanceMockResponse"] | components["schemas"]["PlaidBalanceRealResponse"];
                };
            };
            /** @description Method not allowed (only GET is accepted). */
            405: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Plaid API returned an error. */
            502: {
                headers: {
                    "X-Request-Id": components["headers"]["XRequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
}
