#![cfg(test)]

use super::*;
use soroban_sdk::{
    symbol_short,
    testutils::{Address as _, MockAuth, MockAuthInvoke},
    Address, Bytes, Env, IntoVal, Symbol,
};

// Real UltraHonk artifacts from our circuits (Noir 1.0.0-beta.9 + bb v0.87.0),
// generated by circuits/scripts/build.sh. These exercise the actual on-chain
// BN254 verification path, not a stub.
macro_rules! fixture {
    ($t:literal, $f:literal) => {
        include_bytes!(concat!("../../../fixtures/", $t, "/", $f))
    };
}

fn setup(env: &Env) -> CredentialVerifierClient<'_> {
    let admin = Address::generate(env);
    let id = env.register(CredentialVerifier, (admin,));
    CredentialVerifierClient::new(env, &id)
}

#[test]
fn verifies_kyc() {
    let env = Env::default();
    env.mock_all_auths();
    let c = setup(&env);
    c.set_vk(
        &symbol_short!("kyc"),
        &Bytes::from_slice(&env, fixture!("kyc", "vk")),
    );
    assert!(c.verify_proof(
        &symbol_short!("kyc"),
        &Bytes::from_slice(&env, fixture!("kyc", "proof")),
        &Bytes::from_slice(&env, fixture!("kyc", "public_inputs")),
    ));
}

#[test]
fn verifies_age() {
    let env = Env::default();
    env.mock_all_auths();
    let c = setup(&env);
    c.set_vk(
        &symbol_short!("age"),
        &Bytes::from_slice(&env, fixture!("age", "vk")),
    );
    assert!(c.verify_proof(
        &symbol_short!("age"),
        &Bytes::from_slice(&env, fixture!("age", "proof")),
        &Bytes::from_slice(&env, fixture!("age", "public_inputs")),
    ));
}

#[test]
fn verifies_income() {
    let env = Env::default();
    env.mock_all_auths();
    let c = setup(&env);
    c.set_vk(
        &symbol_short!("income"),
        &Bytes::from_slice(&env, fixture!("income", "vk")),
    );
    assert!(c.verify_proof(
        &symbol_short!("income"),
        &Bytes::from_slice(&env, fixture!("income", "proof")),
        &Bytes::from_slice(&env, fixture!("income", "public_inputs")),
    ));
}

#[test]
fn verifies_jurisdiction() {
    let env = Env::default();
    env.mock_all_auths();
    let c = setup(&env);
    c.set_vk(
        &Symbol::new(&env, "jurisdiction"),
        &Bytes::from_slice(&env, fixture!("jurisdiction", "vk")),
    );
    assert!(c.verify_proof(
        &Symbol::new(&env, "jurisdiction"),
        &Bytes::from_slice(&env, fixture!("jurisdiction", "proof")),
        &Bytes::from_slice(&env, fixture!("jurisdiction", "public_inputs")),
    ));
}

#[test]
fn rejects_tampered_proof() {
    let env = Env::default();
    env.mock_all_auths();
    let c = setup(&env);
    c.set_vk(
        &symbol_short!("kyc"),
        &Bytes::from_slice(&env, fixture!("kyc", "vk")),
    );

    let mut bad = fixture!("kyc", "proof").to_vec();
    bad[5000] ^= 0xff;
    assert!(!c.verify_proof(
        &symbol_short!("kyc"),
        &Bytes::from_slice(&env, &bad),
        &Bytes::from_slice(&env, fixture!("kyc", "public_inputs")),
    ));
}

#[test]
fn rejects_wrong_length_proof() {
    let env = Env::default();
    env.mock_all_auths();
    let c = setup(&env);
    c.set_vk(
        &symbol_short!("kyc"),
        &Bytes::from_slice(&env, fixture!("kyc", "vk")),
    );
    assert!(!c.verify_proof(
        &symbol_short!("kyc"),
        &Bytes::from_array(&env, &[0u8; 16]),
        &Bytes::from_slice(&env, fixture!("kyc", "public_inputs")),
    ));
}

#[test]
#[should_panic]
fn set_vk_rejects_garbage() {
    let env = Env::default();
    env.mock_all_auths();
    let c = setup(&env);
    c.set_vk(&symbol_short!("kyc"), &Bytes::from_array(&env, &[1, 2, 3]));
}

#[test]
#[should_panic]
fn panics_without_vk() {
    let env = Env::default();
    env.mock_all_auths();
    let c = setup(&env);
    c.verify_proof(
        &symbol_short!("age"),
        &Bytes::from_slice(&env, fixture!("kyc", "proof")),
        &Bytes::from_slice(&env, fixture!("kyc", "public_inputs")),
    );
}

// ── RBAC tests ────────────────────────────────────────────────────────────────

#[test]
fn constructor_seeds_admin_role() {
    let env = Env::default();
    env.mock_all_auths();
    let admin = Address::generate(&env);
    let id = env.register(CredentialVerifier, (admin.clone(),));
    let c = CredentialVerifierClient::new(&env, &id);

    assert!(c.has_role(&symbol_short!("admin"), &admin));
    let stranger = Address::generate(&env);
    assert!(!c.has_role(&symbol_short!("admin"), &stranger));
    assert!(!c.has_role(&symbol_short!("upgrader"), &admin));
}

#[test]
fn admin_can_grant_and_revoke_roles() {
    let env = Env::default();
    env.mock_all_auths();
    let c = setup(&env);
    let delegate = Address::generate(&env);
    let stranger = Address::generate(&env);

    // Delegation.
    c.grant_role(&symbol_short!("admin"), &delegate);
    assert!(c.has_role(&symbol_short!("admin"), &delegate));

    // Granting the same role again moves it to the new holder.
    c.grant_role(&symbol_short!("admin"), &stranger);
    assert!(!c.has_role(&symbol_short!("admin"), &delegate));
    assert!(c.has_role(&symbol_short!("admin"), &stranger));

    // Revoking an address that is not the current holder is rejected.
    let res = c.try_revoke_role(&symbol_short!("admin"), &delegate);
    assert!(res.is_err());

    // Revocation.
    c.revoke_role(&symbol_short!("admin"), &stranger);
    assert!(!c.has_role(&symbol_short!("admin"), &stranger));

    // Revoking an unassigned role is a harmless no-op.
    let res = c.try_revoke_role(&symbol_short!("admin"), &stranger);
    assert!(res.is_ok());
}

#[test]
fn grant_revoke_require_admin() {
    let env = Env::default();
    env.mock_all_auths();
    let c = setup(&env);
    let delegate = Address::generate(&env);

    // No auths mocked → the root admin's required auth fails.
    let res = c
        .mock_auths(&[])
        .try_grant_role(&symbol_short!("upgrader"), &delegate);
    assert!(res.is_err());
    let res = c
        .mock_auths(&[])
        .try_revoke_role(&symbol_short!("admin"), &delegate);
    assert!(res.is_err());
}

#[test]
fn set_vk_requires_admin_role() {
    let env = Env::default();
    env.mock_all_auths();
    let admin = Address::generate(&env);
    let id = env.register(CredentialVerifier, (admin.clone(),));
    let c = CredentialVerifierClient::new(&env, &id);
    let delegate = Address::generate(&env);
    let stranger = Address::generate(&env);

    c.grant_role(&symbol_short!("admin"), &delegate);

    let args = (
        &symbol_short!("kyc"),
        Bytes::from_slice(&env, fixture!("kyc", "vk")),
    );

    // The admin-role holder can set a VK…
    c.mock_auths(&[MockAuth {
        address: &delegate,
        invoke: &MockAuthInvoke {
            contract: &id,
            fn_name: "set_vk",
            args: args.clone().into_val(&env),
            sub_invokes: &[],
        },
    }])
    .set_vk(
        &symbol_short!("kyc"),
        &Bytes::from_slice(&env, fixture!("kyc", "vk")),
    );

    // …a non-holder cannot.
    let res = c
        .mock_auths(&[MockAuth {
            address: &stranger,
            invoke: &MockAuthInvoke {
                contract: &id,
                fn_name: "set_vk",
                args: args.into_val(&env),
                sub_invokes: &[],
            },
        }])
        .try_set_vk(
            &symbol_short!("kyc"),
            &Bytes::from_slice(&env, fixture!("kyc", "vk")),
        );
    assert!(res.is_err());

    // After revocation the former holder loses the ability too.
    c.revoke_role(&symbol_short!("admin"), &delegate);
    let res = c
        .mock_auths(&[MockAuth {
            address: &delegate,
            invoke: &MockAuthInvoke {
                contract: &id,
                fn_name: "set_vk",
                args: (
                    &symbol_short!("kyc"),
                    Bytes::from_slice(&env, fixture!("kyc", "vk")),
                )
                    .into_val(&env),
                sub_invokes: &[],
            },
        }])
        .try_set_vk(
            &symbol_short!("kyc"),
            &Bytes::from_slice(&env, fixture!("kyc", "vk")),
        );
    assert!(res.is_err());

    // The root admin (the Admin key holder) can restore the role and act again.
    c.grant_role(&symbol_short!("admin"), &admin);
    assert!(c.has_role(&symbol_short!("admin"), &admin));
    c.mock_auths(&[MockAuth {
        address: &admin,
        invoke: &MockAuthInvoke {
            contract: &id,
            fn_name: "set_vk",
            args: (
                &symbol_short!("kyc"),
                Bytes::from_slice(&env, fixture!("kyc", "vk")),
            )
                .into_val(&env),
            sub_invokes: &[],
        },
    }])
    .set_vk(
        &symbol_short!("kyc"),
        &Bytes::from_slice(&env, fixture!("kyc", "vk")),
    );
}
